### ISSUE TITLE
why do you use Redis Pubsub 

### ISSUE THREAD

**Issue by MaryLilian** [romch007/adonis-pubsub#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by romch007** [comment]
I didn't really choose Redis, I just made sure it was usable. In one of my projects, I was using Redis for storing API tokens and I didn't need advanced PubSub features like RabbitMQ or Kafka, so I used the existing Redis instance to do the PubSub work. In addition, the Redis driver for this project was fairly easy to implement as the Redis provider is native to Adonis. I don't know any special features that Redis might have compared to RabbitMQ/Kafka (it's rather the opposite by the way, RabbitMQ has so much more features).
